### PR TITLE
[feat] Adds stripes pattern shader example

### PR DESCRIPTION
**Pull request by rutvik110**
[feat] Adds stripes pattern shader example. 

https://github.com/Flutter-Bounty-Hunters/flutter_shaders/assets/65209850/4df12083-16fe-4197-a346-7e1cee29afb2

### CODE REVIEW

**Comment by rutvik110** [comment]
@matthew-carroll Made requested updates, lmk if its good.

* Updated the demonstration video to show some practical use cases of the shader.
* Image updated to be 1:1 in ar.

https://github.com/Flutter-Bounty-Hunters/flutter_shaders/assets/65209850/b1165fc9-cecb-4732-9ce0-f80ca5d1596c

**Comment by matthew-carroll** [comment]
@rutvik110 we really want this website to show people how to apply shaders in ways that are likely to help them with their app. That's why the contributing guide asks for an app-relevant demonstration. You'll also see that represented in the shaders currently shown on the website.

Your updated example shows that the shader can be applied to content in an app (text and button), but it still doesn't show a goal that anyone is likely to have. If we're being honest, that text and button look quite unattractive.

Can you find an app use-case where this effect makes things more engaging and attractive instead of less?

**Comment by rutvik110** [comment]
@matthew-carroll I understand that. But the shader in case is build to help you add this stripe pattern with customizations like warp effect, etc within your app. It doesn't have any other goal. How it's used in the app is clearly upto the user.

Right now I don't have any specific use-cases in mind beside adding this as a pattern on text, shapes, backgrounds, etc which it was initially created for. Though I do have this one example where this shader was used to add some spice to this interaction, lmk if this is good enough as an example for it. 

https://github.com/Flutter-Bounty-Hunters/flutter_shaders/assets/65209850/fd828265-c510-4b59-bada-c16a97ba9339

**Comment by matthew-carroll** [comment]
Yeah that video looks more appropriate for app goals. For the square screenshot of that pokemon visual, can you add a quick, static app screen to show it within an app context? For the video, you can show the pokemon circles in isolation - but please try to get as close to @Rahiche's video size and display as possible for consistency.

**Comment by rutvik110** [comment]
@matthew-carroll lmk if these are good to go,

Image:
Screenshot 2024-07-04 at 12 15 12 AM

Video:

https://github.com/Flutter-Bounty-Hunters/flutter_shaders/assets/65209850/622d0010-ab36-40b0-ab7a-f39a17e43759

**Comment by matthew-carroll** [comment]
The square image still doesn't reflect an app use-case and it looks quite large. Please confirm that you've looked at the other screenshot images to understand the expectation, and to set your image size.

For the video, please edit out any beginning and/or ending that shows system chrome and other recording artifacts.

**Comment by rutvik110** [comment]
@matthew-carroll Updated both image and video. Is this better for the screenshot now?

stripes_pattern

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Pull request merged**
